import CSSProvider from "../landing-page/components/CSSProvider";
import Footer from "../landing-page/components/Footer/Footer";
import Navbar from "../landing-page/components/Navbar/index";
import "../landing-page/components/globals.css";

export const metadata = {
    title: "Nextjs Admin Dashboard Template",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>

                <Navbar />
                {children}
                <h1>Footer</h1>
                <Footer />
            </body>
        </html>
    );
}
